import { Accessibility, BarChart3, Code2, LayoutPanelTop, SearchCheck, Smartphone } from "lucide-react";
import { AuditForm } from "@/components/AuditForm";

const groups = [
  [LayoutPanelTop, "Visual system", "Spacing rhythm, component consistency, colors, borders and CTA treatment."],
  [Smartphone, "Responsive behavior", "Desktop and mobile containment, tap targets, clipping and readable layouts."],
  [Accessibility, "Accessibility basics", "Contrast, heading structure, alt text, focus cues and discernible controls."],
  [BarChart3, "Performance indicators", "Requests, errors, redirects, transfer signals and bounded load observations."],
  [SearchCheck, "SEO foundations", "Title, metadata, canonical, robots, schema and sharing readiness."],
  [Code2, "Code boundaries", "Observable CSS signals now; deeper source review only with authorized access."],
];
export default function Home() { return <><header className="shell nav"><a className="brand" href="#top"><span className="brand-mark">H</span>Hermes Audit</a><span className="nav-note">One website, one focused reviewer at a time.</span></header><main id="top"><section className="shell hero"><div><h1>See what your website is <em>telling visitors.</em></h1><p className="hero-copy">A clear, evidence-led review of visual consistency, mobile behavior, accessibility basics, performance signals and SEO foundations.</p><AuditForm /></div><div className="hero-sheet" aria-label="Example audit report"><div className="sheet-content"><div className="sheet-top"><span style={{display:"flex",gap:8,alignItems:"center"}}><span className="status-dot"/> Audit complete</span><span>01:42</span></div><div className="sheet-row"><span>Overall diagnostic score</span><span className="score-orb">74</span></div><div className="sheet-row"><span>Mobile layout</span><b style={{color:"var(--red)"}}>Needs attention</b></div><div className="sheet-row"><span>SEO foundations</span><b style={{color:"var(--green)"}}>Strong</b></div><div className="sheet-row"><span>Screenshot privacy</span><b>24h expiry</b></div></div></div></section><section className="shell section"><div className="section-heading"><h2>A report your client can act on.</h2><p>Measured evidence comes first. AI visual review explains priorities, never fabricates technical findings or ranking guarantees.</p></div><div className="group-grid">{groups.map(([Icon,title,text]) => <article className="group" key={String(title)}><Icon size={23}/><h3>{String(title)}</h3><p>{String(text)}</p></article>)}</div></section></main><footer className="shell footer">Hermes Audit · Public URLs only · Screenshots expire within 24 hours</footer></> }
